name:                finch
version:             0.1.0.0
github:              "tjugdev/finch"
license:             BSD3
author:              "Tristan Jugdev"
maintainer:          "tjugdev@gmail.com"
copyright:           "Tristan Jugdev"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tjugdev/finch#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- mtl
- split
- monad-loops
- random
- safe
- optics

library:
  source-dirs: src
  default-extensions:
  - FlexibleInstances
  - OverloadedLabels
  - OverloadedStrings
  - TupleSections
  - TypeSynonymInstances
  - TemplateHaskell
  - DataKinds
  - MultiParamTypeClasses
  - UndecidableInstances
  - TypeFamilies
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Werror
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Wpartial-fields

executables:
  finch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wmissing-export-lists
    - -Wpartial-fields

    dependencies:
    - finch

tests:
  unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - finch
    - hspec
  functional-tests:
    main:                Spec.hs
    source-dirs:         test/functional
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - finch
    - hspec
