{-# LANGUAGE PatternSynonyms #-}
module Commands where

pattern Plus = '+'
pattern Minus = '-'
pattern Mult = '*'
pattern Div = '/'
pattern Mod = '%'
pattern Not = '!'
pattern GreaterThan = '`'
pattern MoveRight = '>'
pattern MoveLeft = '<'
pattern MoveUp = '^'
pattern MoveDown = 'v'
pattern MoveRandom = '?'
pattern HorizontalIf = '_'
pattern VerticalIf = '_'
pattern StringMode = '"'
pattern Duplicate = ':'
pattern Swap = '\\'
pattern PopDiscard = '$'
pattern PopPrintInteger = '.'
pattern PopPrintChar = ','
pattern Bridge = '#'
pattern Put = 'p'
pattern Get = 'g'
pattern PromptInteger = '&'
pattern PromptChar = '~'
pattern Halt = '@'
pattern Noop = ' '
